import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/features/sidebar";
import { BaseContextProvider } from "@/components/context/base-context";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className=" h-full overflow-hidden  relative flex p-[1rem] ">
        <BaseContextProvider>
          <Sidebar />
          <main className=" flex-1 overflow-y-auto custom-scrollbar">
            {" "}
            {children}
          </main>
        </BaseContextProvider>
      </body>
    </html>
  );
}
